package coursework.gui_designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CategoriesFormDesign extends VerticalLayout {
    protected Label titleLabel;
    protected HorizontalLayout captionLayout;
    protected HorizontalLayout fieldLayout;
    protected TextField valueField;
    protected Button addButton;
    protected HorizontalLayout buttonsLayout;
    protected ComboBox<String> valuesCombo;
    protected Button editButton;
    protected Button deleteButton;

    public CategoriesFormDesign() {
        Design.read(this);
    }
}
