package coursework.gui_designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.DateField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainFormDesign extends Panel {
    protected HorizontalLayout headerLayout;
    protected HorizontalLayout toppestLayout;
    protected Image logoImage;
    protected Label infoLabel;
    protected HorizontalLayout searchFieldLayout;
    protected TextField searchField;
    protected Button searchButton;
    protected HorizontalLayout buttonsHeaderLayout;
    protected Button settingsButton;
    protected VerticalLayout loginButtonLayout;
    protected Button userButton;
    protected Button userLinkButton;
    protected HorizontalLayout optionsLayout;
    protected VerticalLayout sortLayout;
    protected RadioButtonGroup<String> sortRadioGroup;
    protected VerticalLayout dateLayout;
    protected HorizontalLayout dateFieldsLayout;
    protected DateField dateFromField;
    protected DateField dateToField;
    protected CheckBox disallowDateCheckbox;
    protected HorizontalLayout bodyLayout;
    protected VerticalLayout categoriesLayout;
    protected Label categoriesLabel;
    protected HorizontalLayout categoriesFieldLayout;
    protected ComboBox<String> categoriesCombo;
    protected Button selectCategoryButton;
    protected Button resetCategoryButton;
    protected Panel categoriesScrollPanel;
    protected RadioButtonGroup<String> categoriesGroup;
    protected VerticalLayout centerLayout;
    protected Label usernameLabel;
    protected Label userTypeLabel;
    protected HorizontalLayout buttonsLayout;
    protected Button userAdsButton;
    protected Button moderationButton;
    protected Button adminButton;
    protected VerticalLayout lastAdsLayout;
    protected Label lastAdsLabel;
    protected Panel lastAdsPanel;
    protected VerticalLayout lastAdsListLayout;
    protected VerticalLayout tagsLayout;
    protected Label tagsLabel;
    protected HorizontalLayout tagsFieldLayout;
    protected ComboBox<String> tagsCombo;
    protected Button selectTagButton;
    protected Button resetTagButton;
    protected Panel tagsScrollPanel;
    protected CheckBoxGroup<String> tagsGroup;

    public MainFormDesign() {
        Design.read(this);
    }
}
