package coursework.gui_designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainFormDesign extends HorizontalLayout {
    protected VerticalLayout categoriesLayout;
    protected Label categoriesLabel;
    protected HorizontalLayout categoriesFieldLayout;
    protected TextField categoriesField;
    protected Button selectCategoryButton;
    protected Panel categoriesScrollPanel;
    protected RadioButtonGroup<String> categoriesGroup;
    protected VerticalLayout centerLayout;
    protected Label usernameLabel;
    protected Label userTypeLabel;
    protected HorizontalLayout buttonsLayout;
    protected Button userAdsButton;
    protected Button moderationButton;
    protected Button adminButton;
    protected VerticalLayout lastAdsLayout;
    protected Label lastAdsLabel;
    protected Panel lastAdsPanel;
    protected VerticalLayout lastAdsListLayout;
    protected VerticalLayout tagsLayout;
    protected Label tagsLabel;
    protected HorizontalLayout tagsFieldLayout;
    protected TextField tagsField;
    protected Button selectTagButton;
    protected Panel tagsScrollPanel;
    protected CheckBoxGroup<String> tagsGroup;

    public MainFormDesign() {
        Design.read(this);
    }
}
