package coursework.gui_designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserSettingsFormDesign extends FormLayout {
    protected Label titleLabel;
    protected TextField loginField;
    protected PasswordField passwordField;
    protected TextField nameField;
    protected InlineDateField dateField;
    protected HorizontalLayout buttonsLayout;
    protected Button submitButton;

    public UserSettingsFormDesign() {
        Design.read(this);
    }
}
