package coursework.gui_forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdShortFormDesign extends Panel {
    protected Label adNameLabel;
    protected HorizontalLayout topLayout;
    protected Image adImage;
    protected Label adShortTextLabel;
    protected HorizontalLayout bottomLayout;
    protected Label categoryLabel;
    protected Label authorLabel;
    protected Button moreInfoButton;

    public AdShortFormDesign() {
        Design.read(this);
    }
}
