package coursework.gui_forms;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HeaderFormDesign extends HorizontalLayout {
    protected Image logoImage;
    protected Label infoLabel;
    protected HorizontalLayout searchFieldLayout;
    protected VerticalLayout searchLayout;
    protected TextField searchField;
    protected Button searchButton;
    protected Button advancedParametersButton;
    protected HorizontalLayout buttonsLayout;
    protected Button settingsButton;
    protected Button userButton;
    protected Button userLinkButton;

    public HeaderFormDesign() {
        Design.read(this);
    }
}
